"""added review status flags

Revision ID: 2a21424aa719
Revises: 
Create Date: 2026-05-30 01:24:44.848778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a21424aa719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_reviewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pwe_reviewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('top_reviewed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_form', schema=None) as batch_op:
        batch_op.drop_column('top_reviewed')
        batch_op.drop_column('pwe_reviewed')
        batch_op.drop_column('manager_reviewed')

    # ### end Alembic commands ###
