"""added pwe reviewed

Revision ID: 3516fc725d0c
Revises: 2a21424aa719
Create Date: 2026-05-30 01:56:35.355518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3516fc725d0c'
down_revision = '2a21424aa719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pwe_reviewed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager_form', schema=None) as batch_op:
        batch_op.drop_column('pwe_reviewed')

    # ### end Alembic commands ###
